// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EFTask2.Entities
{
    public partial class Frontend
    {
        public string UserName { get; set; }

   
        public string PassWord { get; set; }
    }
}