// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EFTask2.Entities
{  //EF core no longer validate objects or models before save changes
    //EF use assumption from UI
    //EF 6 do validation
    //To enforce validation look at the code 48:10 => override savechanges
    public partial class Kitchen
    {
       /* [MaxLength(50)]
        [Key]
        [Required]*/
        public string UserName { get; set; }

      /*  [MaxLength(50)]
        [Required]*/
        public string PassWord { get; set; }
    }
}